bombasticSlacks/Aspirant

- TODO.md
Todo list should be part of the repository, maybe move to projects at some point, but for now, this is a fine solution.
> Migrated my TODO list

- Game/Character-Creation.md
- Game/Character-Development.md
- Game/Chronicler.md
- Game/Combat-Training.md
- Game/Combat.md
- Game/Diviner.md
- Game/Flurry.md
- Game/Hunter.md
- Game/Leader.md
- Game/Performer.md
- Game/Scientist.md
- Game/Services.md
- Game/Shadow.md
- Game/Stats.md
- Game/Telling-The-Story.md
- TODO.md
Moved to a Power stat, as too many abilities would get unwieldy otherwise. 
Details for training and training types.
> Migrate to unified Power stat

- Game/Chronicler.md
- Game/Craftsman.md
- Game/Doctor.md
- Game/How-To-Play.md
- Game/Resources.md
- Game/Telling-The-Story.md
- Game/Weapons.md
- Game/Worker.md
- TODO.md
Activities were taking *way* too much downtime, should now be meaningful and lead to less wasted time.
Changed wording on the relevant trainings and stuff.
Rework to internal monologue, and some definitions snuck in too.
> Less Evening Activities

- Game/Performer.md
- Game/Scientist.md
- Game/Shadow.md
- Game/Skills.md
- Game/Telling-The-Story.md
- Game/Trades-Training.md
- TODO.md
Explain how much people pay for work done.
> Production Work Pay Explanation

- Game/Armour.md
- Game/Bastion.md
- Game/Combat-Training.md
- Game/Combat.md
- Game/Designing-Armour.md
- Game/Designing-Weapons.md
- Game/Injury.md
- Game/Weapons.md
Added a bunch of new key wording to armour to help clear it up, as well as some examples.
Also moved un-needed info out of the weapons, and armour pages and into the designing pages.
> Keyworded Armour

- Game/Acrobatics.md
- Game/Channel.md
- Game/Converse.md
- Game/Crafting.md
- Game/Fitness.md
- Game/How-To-Play.md
- Game/Husbandry.md
- Game/Knowledge.md
- Game/Marksmanship.md
- Game/Medicine.md
- Game/Melee.md
- Game/Perception.md
- Game/Perform.md
- Game/Ritual.md
- Game/Science.md
- Game/Subterfuge.md
- Game/_includes/title.html
- Game/_sass/base.scss
@KatherineLizHall helped with some style review for the site.
> Apply suggestions from style review

- TODO.md
Couple of finished things on the TODO list marked as complete.
> Update Todo list

- .github/workflows/space-check.yml
- Game/Worlds/Post-Calamity/Argent Hold.md
- Game/Worlds/Post-Calamity/Argent-Hold.md
- Game/Worlds/Post-Calamity/Hooks.md
- Game/Worlds/Post-Calamity/Post-Calamity.md
- Game/Worlds/Post-Calamity/Session-1.md
Makes sure that no files have spaces in the name
> Space check validation

- Game/Doctor.md
- Game/Scientist.md
- Game/Skills.md
- Game/Telling-The-Story.md
New type of skill test related to short-term goals the character is working towards with a big payoff.
Added relevant trainings for projects and changed current trainings.
> Added rules for projects

- Game/Combat-Training.md
- Game/Hunter.md
- Game/Magic-Training.md
- Game/Performer.md
Joyful Traveller renamed to Drink For Free since it's more obvious.
> Few fixes and keywordings

- Game/Character-Development.md
- Game/Composure.md
- Game/Doctor.md
- Game/Injury.md
- Game/Leader.md
- Game/Stats.md
Removed Heroism, replaced with another skill off resolve called composure
Added pure benefits as your character levels up.
> Composure Skill and Progression

- Game/Adventurers.md
- Game/Classes.md
- Game/Combat-Training.md
- Game/Combat.md
- Game/Craftsman.md
- Game/Doctor.md
- Game/Humble-Beginnings.md
- Game/Hunter.md
- Game/Marksman.md
- Game/Skills.md
- Game/Sport.md
- Game/Stats.md
Added a new strength skill sport for wrestling, playing sports, and throwing.
Added another skill point to all characters from character start.
Added some misc. copy
> Added the sports skill

- Game/Designing-Storage.md
- Game/Magic-Training.md
- Game/Worlds/Goose/Dora.md
- Game/Worlds/Goose/G-Session-2.md
- Game/Worlds/Post-Calamity/Argent-Hold.md
- Game/Worlds/Post-Calamity/Calamity.md
- Game/Worlds/Post-Calamity/Crosshaven.md
- Game/Worlds/Post-Calamity/Dorna.md
- Game/Worlds/Post-Calamity/Hooks.md
- Game/Worlds/Post-Calamity/Monsters.md
- Game/Worlds/Post-Calamity/Post-Calamity.md
- Game/Worlds/Post-Calamity/Session-0.md
- Game/Worlds/Post-Calamity/Session-1.md
- Game/Worlds/Post-Calamity/Session-2.md
- Game/Worlds/Post-Calamity/Session-3.md
- Game/Worlds/Post-Calamity/Session-4.md
- Game/Worlds/Post-Calamity/Snowcrest.md
- Game/Worlds/Post-Calamity/Wayside.md
- Game/Worlds/Worlds.md
Also snuck in nav for Calamity
> Updates for session 2 goose

- Game/Home.md
For anyone browsing the site that wasn't introduced by me, should include more clear details.
> Updated Details on Home

- Game/Academic.md
- Game/Arcanist.md
- Game/Bits.md
- Game/Brawler.md
- Game/Character-Development.md
- Game/Dynamist.md
- Game/Flora.md
- Game/Hide.md
- Game/Homebrew.md
- Game/Knight.md
- Game/Labourer.md
- Game/Liquid.md
- Game/Lore.md
- Game/Materials.md
- Game/Mercenary.md
- Game/Metal.md
- Game/Mystic.md
- Game/Resonant.md
- Game/Rogue.md
- Game/Services.md
- Game/Shaper.md
- Game/Skills.md
- Game/Star.md
- Game/Terminology.md
- Game/Textiles.md
- Game/Wanderer.md
- Game/Wood.md
- Game/Worlds/Goose/Dora.md
- Game/Worlds/Goose/Pale-Elves.md
- Game/Worlds/Worlds.md
Fixed some organization for the website
> Website cleanup

- .obsidian/app.json
- Game/Activities.md
- Game/Example-Gear.md
- Game/Gear.md
- Game/Labourer.md
- Game/Telling-The-Story.md
- Game/Terminology.md
* Updated the gear table with clear syntax.
* Trying a new TOC.
* Updated prices to match the internal world.
> Updated the Gear Table

- Game/Example-Armour.md
Added a TOC for armour and alphabetized.
> Table Of Contents For Armour

- .github/config/wordlist.txt
- Game/Academic.md
- Game/Armour.md
- Game/Mercenary.md
- Game/Mystic.md
- Game/Stats.md
> Additional Cleanup

- Game/Agility.md
- Game/Combat.md
- Game/How-To-Play.md
- Game/Intelligence.md
- Game/Mercenary.md
- Game/Mystic.md
- Game/Running-The-Game.md
- Game/Star.md
- Game/Stats.md
- Game/Terminology.md
Closes #88 
Removed Initiative as a unique roll, it is now just a reflexes skill test.
The other trainings related to initiative now become substitute trainings for using different skills.
> Initiative Cleanup

- .github/config/wordlist.txt
- .obsidian/app.json
- Game/Academic.md
- Game/Arcanist.md
- Game/Example-Armour.md
- Game/Magic-Items.md
- Game/Magic-Storage.md
- Game/Services.md
- Game/Stats.md
- Game/Terminology.md
Added rules for binding magic items to yourself including scientific activation.
Added enchanted bags.
closes #110
> Magic Item rules

- Game/Magic-Modifiers.md
> Magic Distance Updates

- Game/Academic.md
- Game/Activities.md
- Game/Brawler.md
- Game/Character-Development.md
- Game/Character-Milestones.md
- Game/Communication.md
- Game/Intelligence.md
- Game/Magic-Items.md
- Game/Mercenary.md
- Game/Rogue.md
- Game/Spirit.md
- Game/Star.md
- Game/Stats.md
- Game/Terminology.md
- Game/Training-Chopping-Block.md
- Game/Wanderer.md
Stats that are a maximum now use max
> Make stats use "max"

- Game/Example-Comestibles.md
Custom comestibles area began, starting with custom munitions available for purchase/crafting.  Table structure is a lil awkward for some of the larger effects, so I'll redo the structure when I add the munition modifiers area.
> Custom comestibles

- Game/Attack-Bonuses.md
- Game/Brawler.md
- Game/Combat.md
- Game/Effects.md
- Game/Knight.md
- Game/Mercenary.md
- Game/Reacting-To-Attacks.md
- Game/Rogue.md
- Game/Special-Combat-Actions.md
- Game/Terminology.md
- Game/Weapon-Traits.md
Migrated some game terminology to just be considered effects.
> terminology to effects

- Game/Academic.md
- Game/Dynamist.md
- Game/Effects.md
- Game/Knight.md
- Game/Labourer.md
- Game/Mercenary.md
- Game/Shaper.md
- Game/Skills.md
- Game/Weapon-Traits.md
Resolved multiple outstanding issues.
Fixes #139 
Fixes #138 
Fixes #126 
Fixes #125 
Fixes #116 
Fixes #134
> Issues Cleanup

- Game/Worlds/Post-Calamity/Causdin.md
- Game/Worlds/Post-Calamity/Hooks.md
- Game/Worlds/Post-Calamity/Session-13.md
- Templates/Settlement.template.md
Notes for session 13 of Calamity.
> Session 13 Notes

- Game/Mercenary.md
- Game/Monster-Types/Demons.md
- Game/Worlds/Goose/Bridge-Of-Lady-Vanna.md
- Game/Worlds/Goose/G-Session-7.md
- Game/Worlds/Goose/G-Session-8.md
- Game/Worlds/Goose/Goose-Hooks.md
- Game/Worlds/Goose/Pale-Elves.md
- Game/Worlds/Post-Calamity/Causdin.md
- Game/Worlds/Post-Calamity/Greg-Colter.md
- Game/Worlds/Post-Calamity/Hooks.md
- Game/Worlds/Post-Calamity/Session-12.md
- Game/Worlds/Post-Calamity/Session-13.md
- Game/Worlds/Post-Calamity/Session-14.md
- Game/Worlds/Post-Calamity/Vampire-Lords.md
Updates for the last Goose and Calamity session
> Two Sessions Updated

- Game/Academic.md
- Game/Activities.md
- Game/Additional-Attributes.md
- Game/Adventurers.md
- Game/Brawler.md
- Game/Character-Development.md
- Game/Character-Milestones.md
- Game/Designing-Armour.md
- Game/Knight.md
- Game/Magic-Items.md
- Game/Magic-Modifiers.md
- Game/Mercenary.md
- Game/Mystic.md
- Game/Rogue.md
- Game/Services.md
- Game/Star.md
- Game/Telling-The-Story.md
- Game/Training-Chopping-Block.md
- Game/Wanderer.md
- Game/Worlds/Goose/Pale-Elves.md
Did some renaming, moved aspirant specific stuff to aspirant. Etc.
> Updated Core and Moved Aspirant Rules To Aspirant

- Game/Activities.md
- Game/Adventurers.md
- Game/Character-Milestones.md
- Game/Knight.md
- Game/Mercenary.md
- Game/Rogue.md
- Game/Shaper.md
- Game/Star.md
- Game/Wanderer.md
- Game/Worlds/Post-Calamity/Hooks.md
- Game/Worlds/Post-Calamity/Session-15.md
- Game/Worlds/Post-Calamity/Vampire-Lords.md
Session 15 notes plus some link fixes.
> Calamity Session 15
